language: node_js
node_js:
  - 7
sudo: false
cache:
  directories:
    - node_modules
script:
  - unset CI
  - npm run build
install:
- npm install
- npm install -g react-scripts
- cd api/ && npm install && cd ..
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master