language: node_js
node_js:
  - 7
cache:
  directories:
    - node_modules
script:
  - unset CI
  - npm run build
install:
- npm install
- npm install -g react-scripts
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN