language: node_js
node_js:
  - 7
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
install:
- npm install -g react-scripts
- npm install -g firebase-tools
after_success:
- firebase deploy  - project return-to-sleep - token $FIREBASE_TOKEN.